version: '2'
services:
  gsicrawler:
    build: ./gsicrawler
    ports:
     - "5555:5555"
     - "5000:5000"
    networks:
      - participation
    depends_on:
      - redis
      - elasticsearch
    env_file: gsicrawler/.env
    environment:
      - GSICRAWLER_BROKER=redis://redis:6379/
      - GSICRAWLER_RESULT_BACKEND=redis://redis:6379/

  orchestrator:
    build: .
    volumes: 
      - ./app:/usr/src/app
    ports:
     - "8082:8082"
    networks:
      - participation
    env_file: .env


  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    volumes:
     - ./fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=fusekiparticipation
    networks:
      - participation

  senpy:
    build: ./senpy-plugins
    command: --plugins-folder /plugins
    ports:
     - "8007:5000"
    networks:
      - participation
    volumes:
      - ./senpy-plugins:/plugins

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - 'http.cors.allow-origin=*'
      - discovery.type=single-node
      - "xpack.ml.enabled=false"
    volumes:
      - esdata:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - participation
      - elastic-kibana
  
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    # command: sh -c './bin/kibana-plugin install file:///usr/share/kibana/plugins/kibana-dashboard-custom-css.zip && exec /usr/local/bin/kibana-docker'
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elastic-kibana
    # volumes:
    #   - /tmp:/usr/share/kibana/plugins

  redis:
    image: redis
    networks:
      - participation

networks:
  participation:
    driver: bridge
  elastic-kibana:
    driver: bridge

volumes:
  esdata:


